### ISSUE TITLE
Some of the endpoints are not available

### ISSUE THREAD

**Issue by Uberariy** [Owen3H/EarthMC-Toolkit-Website#3]
Trying to get data about all players. https://emctoolkit.vercel.app/api cite lists available endpoints. Trying to get https://emctoolkit.vercel.app/api/aurora/allplayers results in code 503, although https://emctoolkit.vercel.app/api/aurora/onlineplayers is okay.

Actually I need only the data about all the mayors (~2700 people). Something similar that ```/player PLAYERNAME``` provides.

**Comment by Owen3H** [comment]
Thanks for bringing this to my attention. I have decided to delete the `/allplayers` endpoint as it does not provide anything useful now that there is an [official API](https://earthmc.net/docs/api/) hosted by EarthMC. 

For your use case, I suggest you use the `/residents` to grab mayors, then any other data needed can be acquired by querying the aforementioned official API.
